# Generated by Django 6.0.1 on 2026-01-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('canaddbook', 'Can add book'), ('canchangebook', 'Can change book'), ('candeletebook', 'Can delete book'))},
        ),
    ]
